const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,LOG_DIR=path.join(ROOT,'data'),LOG_FILE=path.join(LOG_DIR,'draws.json'),COOLDOWN_MS=5*60*1000;
const PRIZES=[{id:'marble_50',name:'50颗弹珠',probability:30},{id:'marble_100',name:'100颗弹珠',probability:35},{id:'marble_150',name:'150颗弹珠',probability:10},{id:'marble_200',name:'200颗弹珠',probability:3},{id:'point_1',name:'1积分卡',probability:15},{id:'point_5',name:'5积分卡',probability:4},{id:'point_10',name:'10积分卡',probability:2},{id:'point_15',name:'15积分卡',probability:1}];
const lastDrawByVisitor=new Map();fs.mkdirSync(LOG_DIR,{recursive:true});if(!fs.existsSync(LOG_FILE))fs.writeFileSync(LOG_FILE,'[]','utf8');
try{for(const record of JSON.parse(fs.readFileSync(LOG_FILE,'utf8'))){if(record.visitor_id&&record.draw_time)lastDrawByVisitor.set(record.visitor_id,new Date(record.draw_time).getTime())}}catch(_){}
function json(res,status,payload){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(payload))}
function getVisitorId(value){if(typeof value!=='string'||value.length<8||value.length>100)return null;return value.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100)||null}
function remainingFor(id){const last=lastDrawByVisitor.get(id)||0;return Math.max(0,Math.ceil((last+COOLDOWN_MS-Date.now())/1000))}
function pickPrize(){const roll=crypto.randomInt(0,100);let cursor=0;for(const prize of PRIZES){cursor+=prize.probability;if(roll<cursor)return prize}return PRIZES[PRIZES.length-1]}
function readBody(req){return new Promise((resolve,reject)=>{let body='';req.on('data',chunk=>{body+=chunk;if(body.length>10000)req.destroy()});req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function logDraw(record){try{const records=JSON.parse(fs.readFileSync(LOG_FILE,'utf8'));records.push(record);fs.writeFileSync(LOG_FILE,JSON.stringify(records,null,2),'utf8')}catch(_){} }
function serveFile(req,res,pathname){const requested=pathname==='/'?'/index.html':pathname,safePath=path.normalize(path.join(ROOT,requested));if(!safePath.startsWith(ROOT))return json(res,403,{message:'Forbidden'});fs.readFile(safePath,(error,data)=>{if(error)return json(res,404,{message:'Not found'});const ext=path.extname(safePath),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-cache'});res.end(data)})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(req.method==='GET'&&url.pathname==='/api/prizes')return json(res,200,PRIZES);if(req.method==='GET'&&url.pathname==='/api/status'){const id=getVisitorId(url.searchParams.get('visitorId'));if(!id)return json(res,400,{message:'visitorId required'});const remainingSeconds=remainingFor(id);return json(res,200,{canDraw:remainingSeconds===0,remainingSeconds})}if(req.method==='POST'&&url.pathname==='/api/draw'){const body=await readBody(req),id=getVisitorId(body.visitorId);if(!id)return json(res,400,{success:false,message:'visitorId required'});const remainingSeconds=remainingFor(id);if(remainingSeconds>0)return json(res,429,{success:false,code:'COOLDOWN',remainingSeconds});const prize=pickPrize(),now=Date.now();lastDrawByVisitor.set(id,now);logDraw({id:crypto.randomUUID(),visitor_id:id,prize:prize.name,draw_time:new Date(now).toISOString(),ip:req.socket.remoteAddress||'',user_agent:req.headers['user-agent']||''});return json(res,200,{success:true,prize:{id:prize.id,name:prize.name},cooldownSeconds:COOLDOWN_MS/1000})}if(req.method==='GET')return serveFile(req,res,url.pathname);return json(res,404,{message:'Not found'})}catch(_){return json(res,500,{success:false,message:'Server error'})}});
server.listen(PORT,()=>console.log(`疯狂弹珠 running at http://localhost:${PORT}`));
